# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fc7ba0bf17173f262297d003a6ae63cded26bb0aef618dd02a5c01837a590bb6d3b3ac5ed6da1981229e65d74bda3bf21bf965d00733c0db096aab19d56a6b9

test:
  secret_key_base: 26d618d76efd886b88b05767d3540f9349bdad548407ce2d3aa9a1eaa77481e66eb559c56a0c8b35b117adb4a5c678ac7a20088c763d9a1dca77147b74cf3d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
